"""empty message

Revision ID: 1e88757f467f
Revises: 543721aeaba1
Create Date: 2021-10-19 16:55:57.779108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e88757f467f'
down_revision = '543721aeaba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('prefix', sa.String(), nullable=False))
    op.add_column('course', sa.Column('number', sa.String(), nullable=False))
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('course', 'number')
    op.drop_column('course', 'prefix')
    # ### end Alembic commands ###
