"""empty message

Revision ID: 543721aeaba1
Revises: 7a8620fcdcb6
Create Date: 2021-10-19 16:39:28.988458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543721aeaba1'
down_revision = '7a8620fcdcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('reviewer', sa.String(), nullable=True))
    op.alter_column('review', 'professor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'professor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('review', 'reviewer')
    # ### end Alembic commands ###
