"""empty message

Revision ID: 66427294c06f
Revises: 4e5f023b5482
Create Date: 2021-11-02 19:47:16.664009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66427294c06f'
down_revision = '4e5f023b5482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_name_key', 'course', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_name_key', 'course', ['name'])
    # ### end Alembic commands ###
