"""empty message

Revision ID: cfb5b8708bfa
Revises: 1e88757f467f
Create Date: 2021-10-19 18:42:44.592971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb5b8708bfa'
down_revision = '1e88757f467f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syllabus', 'professor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllabus', sa.Column('professor', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
